### ISSUE TITLE
panic explanation could use some fleshing out

### ISSUE THREAD

**Issue by steveklabnik** [stevedonovan/gentle-intro#12]
> The first C program I wrote (on an DOS PC) took out the whole computer. Unix systems always behaved better, and only the process died with a segfault. Why is this worse than a Rust (or Go) program panicking? Because the panic happens when the original problem happens, not when the program has become hopelessly confused and eaten all your homework.

This is true, but it's not the root of the issue: the root is that panics don't introduce memory unsafety, nor undefined behavior. This means a panic can't cause a security issue in the same way a segfault can.

**Comment by stevedonovan** [comment]
Yes, that was the intention - I must just make it clearer. I have lived through enough C++ segfaults to know the difference ;)
