### ISSUE TITLE
Typo input -> output

### ISSUE THREAD

**Issue by iwburns** [stevedonovan/gentle-intro#18]
I'm submitting this before I create a PR just in case I'm misunderstanding what I'm reading, but I believe there's a typo in 1-basics.md:

`Which won't produce any input. But change 42 to 40:`
should probably read:
`Which won't produce any output. But change 42 to 40:`

Mind if I submit a PR for this?

EDIT: I also just found this:
`how to write an slice type`
should probably read:
`how to write a slice type`
or possibly even:
`how to write a slice's type`

Any thoughts/preference on that one?

**Comment by stevedonovan** [comment]
Well spotted. Yep, they all need fixing, so please go ahead with a PR
