### ISSUE TITLE
Mismatched types error

### ISSUE THREAD

**Issue by Yamose** [stevedonovan/gentle-intro#19]
Had an error trying:

    let last = slice.get(5).unwrap_or(-1);

This worked:

    let last = slice.get(5).unwrap_or(&-1):

Full code:
```
fn main() {
    let ints = [1, 2, 3, 4, 5];
    let slice = &ints;
    let first = slice.get(0);
    let last = slice.get(5);

    println!("first: {}", first.unwrap_or(&-1));
    println!("last: {}", last.unwrap_or(&-1));
}
```
Thanks for the tutorial.

**Comment by stevedonovan** [comment]
Ah, and the moral of the story - put everything through the compiler! Yes, `get` can only return a reference, and `unwrap_or` requires exact match. I will fix, thanks.

**Comment by andradei** [comment]
This could be closed, since a fix was pushed.
