### ISSUE TITLE
1-basics: slice.get().unwrap_or() does not compile

### ISSUE THREAD

**Issue by jaystrictor** [stevedonovan/gentle-intro#21]
In section [Optional Values](https://github.com/stevedonovan/gentle-intro/blob/master/1-basics.md#optional-values) the provided example does not compile for me with rustc 1.16.0.

```rust
fn main() {
    let ints = [1, 2, 3, 4, 5];
    let slice = &ints;

    let maybe_last = slice.get(5);
    let last = if maybe_last.is_some() {
        maybe_last.unwrap()
    } else {
        -1
    };
}
```

The error message is
`error[E0308]: if and else have incompatible types`.

If I change the else-clause to
```rust
    } else {
        &-1
    };
```

the error message is `error: borrowed value does not live long enough`.

**Comment by stevedonovan** [comment]
Yes, `get` always returns a reference, so the neatest way I can think of is:

```rust
    let maybe_last = slice.get(5);
    let mut last = -1;
    if maybe_last.is_some() {
        last = *maybe_last.unwrap();
    }
```
or better:

```rust
    let maybe_last = slice.get(5);
    let last = if maybe_last.is_some() {
        *maybe_last.unwrap()
    } else {
        -1
    }
```
No way around that dereference `*`, except by indexing twice:
```rust
    let maybe_last = slice.get(5);
    let last =  if slice.get(5).is_some() {
        slice[5]
    } else {
         -1
   }
```
I'll see what's easier to explain....

**Comment by stevedonovan** [comment]
I've gone for the 2nd option, and made previous mention of references.

**Comment by jaystrictor** [comment]
Nice. Thanks for the quick fix.
