### ISSUE TITLE
Grammar error @ Structs-enums-lifetimes

### ISSUE THREAD

**Issue by blasrodri** [stevedonovan/gentle-intro#22]
[Structs and Enums](https://raw.githubusercontent.com/stevedonovan/gentle-intro/master/2-structs-enums-lifetimes.md)

Original:
since it contains a allocated
pointer to the data, and always has a fixed size.

New:
since it contains **an** allocated
pointer to the data, and always has a fixed size.

**Comment by stevedonovan** [comment]
Thanks for the sharp eye

**Comment by blasrodri** [comment]
Thank you for this **awesome** repo.
