### ISSUE TITLE
make it easy to build (with mdbook)

### ISSUE THREAD

**Issue by tshepang** [stevedonovan/gentle-intro#39]
mdbook expects to find SUMMARY.md inside `./src`, so how about renaming `src/` to `code/`
and moving content to `src/`. I just checked... works well. I see there will ne a need for further small changes. I can submit a PR if this looks like the right idea.

**Comment by stevedonovan** [comment]
I like this, because then it's easy for everyone to build the book. I was using symlinks - ouch!
