### ISSUE TITLE
plan of transalte Chinese 🇨🇳

### ISSUE THREAD

**Issue by chinanf-boy** [stevedonovan/gentle-intro#69]
## translate to chinese

github source >> https://github.com/chinanf-boy/gentle-intro

web site >> https://chinanf-boy.github.io/gentle-intro

**Comment by stevedonovan** [comment]
I am very happy that you decided to do this!

**Comment by chinanf-boy** [comment]
May you add gentle-intro repo's readme.md file

It will show more detail about you and your book to Readers

**Comment by chinanf-boy** [comment]
@stevedonovan What would you think 😊
