### ISSUE TITLE
1-basics: introducing traits

### ISSUE THREAD

**Issue by steveklabnik** [stevedonovan/gentle-intro#8]
> AddAssign is the name of the trait implementing the += operator,

This is the first time you mention traits, and you don't explain them here.

**Comment by stevedonovan** [comment]
Yes, well spotted. There's a bit of a chicken-and-egg problem here - that things are mentioned before they are explained. This is a good spot to talk a little about traits and operators.

**Comment by steveklabnik** [comment]
Trust me, I feel your pain :)
