### ISSUE TITLE
How to use executable code

### ISSUE THREAD

**Issue by hajsf** [stevedonovan/gentle-intro#90]
Hi.. well this is not a bug reporting, this is a question and request for assistant.

How you got the you write at `.md` a:

![image](https://user-images.githubusercontent.com/46838626/64420670-76ef7b00-d0a8-11e9-860b-385fdf39996e.png)

To appear as executable code at the book:

![image](https://user-images.githubusercontent.com/46838626/64420738-9b4b5780-d0a8-11e9-8a5a-b10eb8ef571d.png)

What shall I do to write a code like this, I noticed this in many `books` about rust, but do not know what they call it, and how they do it :)

Thanks

**Comment by tshepang** [comment]
mdbook does it for you magically, so long as you annotate the block as Rust (````rust`). Look at the source https://raw.githubusercontent.com/stevedonovan/gentle-intro/master/src/1-basics.md.
